### ISSUE TITLE
How to configure nunjucks, e.g. add filters

### ISSUE THREAD

**Issue by davisford** [SamyPesse/tpl-emails#1]
Hi, in the old swig-emails, you could do this:

``` javascript

var swig = require('swig');
swig.setFilter('foo', function (in) { return 'foo' + in; });

var emails = new SwigEmails({
  root: path.join(__dirname, 'templates'),
  swig: swig
});
```

But in the nunjucks version, you [always require nunjucks in the constructor](https://github.com/SamyPesse/tpl-emails/blob/master/lib/index.js#L14).

Maybe I'm missing something -- perhaps when you call `require('nunjucks').addFilter(...)` the filter is added globally so it isn't necessary to send it into `TplEmails` -- is this the case?

Otherwise, I think you should allow client to pass in a reference to a pre-configured nunjucks instance or else expose it as a setter/getter on the object so it could be overwritten.

**Comment by SamyPesse** [comment]
The solution is to do:

``` js
var TplEmails = require("tpl-emails");
var nunjucks = require("nunjucks");

var env = new nunjucks.Environment(new nunjucks.FileSystemLoader("./mytemplates"));
env.addFilter("test", function(s) {
    return "Test"+s;
});

var emails = new TplEmails({
    render: env.render.bind(env)
});
```

**Comment by SamyPesse** [comment]
Basically, you can use any render function you want to: https://github.com/SamyPesse/tpl-emails/blob/master/lib/index.js#L13
